GET http://localhost:3000

### checking contacts locally
GET http://localhost:3000/contacts

### checking a specific contacts locally
GET http://localhost:3000/contacts/67931a10f5b8c1283bf342da

### creating a contacts
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "test1@gmail.com",
    "favoriteColor": "grey",
    "birthday": "12/12/20"
}

### changing a contacts
PUT http://localhost:3000/contacts/67a59f46eef680eb0beac3b4 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Craig",
    "lastName": "Smith",
    "email": "test41@test.com",
    "favoriteColor": "Blue",
    "birthday": "12/12/20"
}

### deleting a contacts
DELETE http://localhost:3000/contacts/67a59e7886d37f8162611ab8 HTTP/1.1


### checking employees locally
GET http://localhost:3000/employees

### checking a specific employees locally
GET http://localhost:3000/employees/67a615f9b0fad2c4c3644d41

### creating a employees
POST http://localhost:3000/employees HTTP/1.1
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Rouge",
    "email": "test1@gmail.com",
    "favoriteColor": "grey",
    "birthday": "12/12/20",
    "department": "Sales",
    "position": "Manager"
}

### changing a employees
PUT http://localhost:3000/employees/67a615f9b0fad2c4c3644d41 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Matt",
    "lastName": "Rouge",
    "email": "test1@test.com",
    "favoriteColor": "purple",
    "birthday": "12/12/20",
    "department": "Sales",
    "position": "Manager"
}

### deleting a employees
DELETE http://localhost:3000/employees/67a615f9b0fad2c4c3644d41 HTTP/1.1