GET http://localhost:3000

### checking users locally
GET http://localhost:3000/user

### checking a specific user locally
GET http://localhost:3000/user/67931a10f5b8c1283bf342da

### creating a user
POST http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Smith",
    "email": "test1@test.com",
    "favoriteColor": "Blue",
    "birthday": "12/12/20"
}

### changing a user
PUT http://localhost:3000/user/67936e264c688155f17d299f HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mark",
    "lastName": "Smith",
    "email": "test1@test.com",
    "favoriteColor": "Blue",
    "birthday": "12/12/20"
}

### deleting a user
DELETE http://localhost:3000/user/67936e264c688155f17d299f HTTP/1.1